#!/usr/bin/env python

from itertools import cycle

COLUMN = 4 * 20 + 2
RAW = 20

for i, c in enumerate(cycle(r"/ \_")):
    print(c, end="")
    if i % COLUMN == COLUMN - 1:
        print()
        if i == RAW * COLUMN - 1:
            break
