#!/bin/bash
sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

while [ "$(cat /proc/acpi/button/lid/LID/state)" == "state:      open" ]; do
  sleep 1
done

while [ "$(cat /proc/acpi/button/lid/LID/state)" == "state:      closed" ]; do
  sleep 2
done

sudo systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target
