#!/usr/bin/env bash

toggle() {
	if pidof mihomo >/dev/null; then
		close
	else
		start
	fi
}

close() {
	if [ "$PERSIST" ]; then
		sudo systemctl disable --now mihomo.service
		sudo systemctl enable --now systemd-resolved.service
		echo mihomo closed\(persist\)
	else
		sudo systemctl stop mihomo.service
		sudo systemctl start systemd-resolved.service
		echo mihomo closed
	fi
}

start() {
	if [ "$PERSIST" ]; then
		sudo systemctl disable --now systemd-resolved.service
		sudo systemctl enable --now mihomo.service
		echo start\(persist\) mihomo "(pid: $(pidof mihomo))"
	else
		sudo systemctl stop systemd-resolved.service
		sudo systemctl start mihomo.service
		echo start mihomo "(pid: $(pidof mihomo))"
	fi
}

query() {
	MIHOMO_PERSIST_STATUS="$(systemctl is-enabled mihomo.service)"
	if pidof mihomo >/dev/null; then
		echo "mihomo status: On (preset: $MIHOMO_PERSIST_STATUS)"
	else
		echo "mihomo status: Off (preset: $MIHOMO_PERSIST_STATUS)"
	fi
}

# while getopts 'p' OPTS; do
# 	case $OPTS in
# 	p) PERSIST=true ;;
# 	*) ;;
# 	esac
# done
if [[ "$1" == *"-p" ]]; then
	PERSIST=true
fi

if [ -z "$1" ] || [[ "$1" == "toggle"* ]]; then
	toggle
elif [[ "$1" == "close"* ]]; then
	close
elif [[ "$1" == "start"* ]]; then
	start
elif [[ "$1" == "query"* ]]; then
	query
fi
