input {
  numlock_by_default = true

  repeat_delay = 180
  repeat_rate = 50

  touchpad {
    clickfinger_behavior = true
  }
}
gesture = 3, swipe, move,
gesture = 3, pinch, float

general {
  snap {
    enabled = true
    window_gap = 4
    monitor_gap = 5
    respect_gaps = true
  }
}
