### MPV
windowrule = match:class mpv, float on

### Yazi
windowrule = match:class yazi, float on
# TODO: memory window size
windowrule = match:class yazi, size 1280 720

windowrule = match:class zen-beta, match:title 我的足迹, float on

windowrule {
    name = "zen-ricing"
    match:class = zen-beta
    match:initial_title = Zen Browser
    opacity = 0.93 0.93
    rounding = 12
}

# decoration {
#     rounding = 14
#
#     # blur {
#     #     enabled = true
#     #     size = 8
#     #     passes = 3
#     #     new_optimizations = true
#     #     ignore_opacity = false
#     # }
#
#     # shadow {
#     #     enabled = true
#     #     range = 18
#     #     render_power = 3
#     #     color = rgba(00000066)
#     # }
#
#     blur {
#         enabled = true
#         size = 6
#         passes = 3
#         new_optimizations = true
#         # ignore_opacity = false
#     }
#
#     shadow {
#         enabled = true
#         range = 4
#         render_power = 3
#         color = rgba(1a1a1aee)
#     }
# }

# windowrule = match:class .*, opacity 0.94 0.88
