$primary_paletteKeyColor = 4a7ba6
$secondary_paletteKeyColor = 6a7989
$tertiary_paletteKeyColor = 817094
$neutral_paletteKeyColor = 74777c
$neutral_variant_paletteKeyColor = 72777e
$background = 101418
$onBackground = e0e2e8
$surface = 101418
$surfaceDim = 101418
$surfaceBright = 36393e
$surfaceContainerLowest = 0b0f12
$surfaceContainerLow = 181c20
$surfaceContainer = 1c2024
$surfaceContainerHigh = 272a2f
$surfaceContainerHighest = 323539
$onSurface = e0e2e8
$surfaceVariant = 42474e
$onSurfaceVariant = c2c7cf
$inverseSurface = e0e2e8
$inverseOnSurface = 2d3135
$outline = 8c9198
$outlineVariant = 42474e
$shadow = 000000
$scrim = 000000
$surfaceTint = 9bcbfb
$primary = 9bcbfb
$onPrimary = 003353
$primaryContainer = 0e4a73
$onPrimaryContainer = cee5ff
$inversePrimary = 2f628c
$secondary = b9c8da
$onSecondary = 233240
$secondaryContainer = 3a4857
$onSecondaryContainer = d5e4f7
$tertiary = d3bfe6
$onTertiary = 382a49
$tertiaryContainer = 9c89ae
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = cee5ff
$primaryFixedDim = 9bcbfb
$onPrimaryFixed = 001d33
$onPrimaryFixedVariant = 0e4a73
$secondaryFixed = d5e4f7
$secondaryFixedDim = b9c8da
$onSecondaryFixed = 0e1d2a
$onSecondaryFixedVariant = 3a4857
$tertiaryFixed = eedbff
$tertiaryFixedDim = d3bfe6
$onTertiaryFixed = 231533
$onTertiaryFixedVariant = 4f4061
$term0 = 343434
$term1 = 8383ff
$term2 = 44def5
$term3 = 75fcdd
$term4 = 83b0cf
$term5 = 8ea9ee
$term6 = 8bd3f3
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = a9c5d6
$term13 = aabdf8
$term14 = a7e4ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = cfddff
$mauve = 9bc2ff
$red = 97b2ff
$maroon = aebdf1
$peach = e0c2f9
$yellow = d0f9f4
$green = b5e7ff
$teal = bee5ff
$sky = b9e0ff
$sapphire = 91cdff
$blue = 85c2ff
$lavender = aacfff
$klink = 408cc9
$klinkSelection = 408cc9
$kvisited = 4380da
$kvisitedSelection = 4380da
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b7eb
$kpositiveSelection = 00b7eb
$text = e0e2e8
$subtext1 = c2c7cf
$subtext0 = 8c9198
$overlay2 = 797e85
$overlay1 = 666b71
$overlay0 = 555a60
$surface2 = 44494e
$surface1 = 34383d
$surface0 = 22262a
$base = 101418
$mantle = 101418
$crust = 0f1317
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
