if require("nixCatsUtils").isNixCats then return end

local binary = {
  "tree-sitter",
  "ripgrep",
}
local lsps = {
  "jsonls",
  "prettierd",
  "lua_ls",
  "selene",
  "stylua",
  "nixd",
  "statix",
  "deadnix",
  "alejandra",
  "rust_analyzer",
  "clippy",
  "rustfmt",
  "taplo",
}

-- TODO: package(...)
local plugins = {
  "BirdeeHub/lze",
  "BirdeeHub/lzextras",
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  "nvim-treesitter/nvim-treesitter-textobjects",
  "nvim-treesitter/nvim-treesitter-context",
  "RRethy/nvim-treesitter-endwise",
  "Saghen/blink.cmp",
  "saghen/blink.compat",
  "b0o/schemastore.nvim",
  "folke/trouble.nvim",
  "numToStr/Comment.nvim",
  "stevearc/conform.nvim",
  "mfussenegger/nvim-lint",
  "mfussenegger/nvim-dap",
  "rcarriga/nvim-dap-ui",
  "theHamsta/nvim-dap-virtual-text",
  "LiadOz/nvim-dap-repl-highlights",
  "stevearc/overseer.nvim",
  "folke/lazydev.nvim",
  "NTBBloodbath/daylight.nvim",
  "nvim-lualine/lualine.nvim",
  "folke/noice.nvim",
  "MunifTanjim/nui.nvim",
  "rcarriga/nvim-notify",
  "folke/snacks.nvim",
  "folke/which-key.nvim",
  "catppuccin/nvim",
  "xiyaowong/transparent.nvim",
  "NTBBloodbath/sweetie.nvim",
  "folke/neoconf.nvim",
  "nvim-neotest/neotest",
  "nvim-neotest/nvim-nio",
  "nvim-lua/plenary.nvim",
  "echasnovski/mini.icons",
  "saghen/blink.cmp",
  "L3MON4D3/LuaSnip",
  "rafamadriz/friendly-snippets",
  "max397574/better-escape.nvim",
  "nvim-neo-tree/neo-tree.nvim",
  "nvim-tree/nvim-web-devicons",
  "antosha417/nvim-lsp-file-operations",
  "dmmulroy/ts-error-translator.nvim",
  "stevearc/oil.nvim",
  "benomahony/oil-git.nvim",
  "SirZenith/oil-vcs-status",
  "JezerM/oil-lsp-diagnostics.nvim",
  "refractalize/oil-git-status.nvim",
  "goolord/alpha-nvim",
  "karb94/neoscroll.nvim",
  "mrjones2014/smart-splits.nvim",
  { "ThePrimeagen/harpoon", branch = "harpoon2" },
  "folke/flash.nvim",
  "smoka7/hop.nvim",
  "windwp/nvim-ts-autotag",
  "nguyenvukhang/nvim-toggler",
  "abecodes/tabout.nvim",
  "kylechui/nvim-surround",
  "NMAC427/guess-indent.nvim",
  "JoosepAlviste/nvim-ts-context-commentstring",
  "windwp/nvim-autopairs",
  "folke/todo-comments.nvim",
  "kevinhwang91/promise-async",
  "kevinhwang91/nvim-ufo",
  "ahmedkhalf/project.nvim",
}

if vim.version:ge "0.12" then
  -- TODO:
else
  require("nixCatsUtils.catPacker").setup(plugins)
end
