## https://taplo.tamasfe.dev/configuration/#configuration-file

[formatting]
align_entries = true
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = false
compact_arrays = false
compact_inline_tables = false
column_width = 160
indent_tables = false
indent_string = "    "
reorder_keys = false
trailing_newline = true
allowed_blank_lines = 1
crlf = false
