#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]
prepend_keymap = [
    # { on = "q", run = "plugin confirm-quit", desc = "Close the current tab, or quit if it's last" },
    { on = "<C-w>", run = "close", desc = "Close the current tab, or quit if it's last" },
    # Hopping
    { on = "j", run = "arrow 1", desc = "Next file" },
    { on = "k", run = "arrow -1", desc = "Previous file" },
    { on = "<Down>", run = "arrow 1", desc = "Next file" },
    { on = "<Up>", run = "arrow -1", desc = "Previous file" },
    # { on = "K", run = "arrow -5" },
    # { on = "J", run = "arrow 5" },

    # Goto
    { on = [ "g", "r" ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"' },
    { on = [ 'g', 't' ], run = 'shell -- ya emit cd "$(zoxide query tmp)"', desc = "Go tmp" },
    # { on = [ "g", "c" ], run = "plugin vcs-files" },

    # Drop to Shell
    { on = [ "$" ], run = 'shell $SHELL --block', desc = "Open shell here" },

    # # Open gui file manager
    # { on = [ "<C-Space>", "f" ], run = '''shell nemo --block''', desc = "Open gui file manager" },

    # Yank to clipboard
    { on = [ "c", "y" ], run = 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list', desc = "Yank to clipboard" },

    # Drag & Drop
    # { on = "<C-n>", run = 'shell -- dragon-drop -x -i -T %h' },

    # Plugins
    { on = [ "<C-Space>", "d" ], run = "plugin diff", desc = "Diff" },
    { on = [ "<C-Space>", "g" ], run = "plugin lazygit", desc = "Lazygit" },
    { on = [ "c", "p" ], run = "plugin save-clipboard-to-file", desc = "Paste from clipboard and hover" },
    { on = [ "c", "m" ], run = "plugin chmod" },
    { on = [ "c", "a" ], run = "plugin ouch", desc = "compress" },
    { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

    { on = "M", run = "plugin mount", desc = "Mount" },
    # { on = [ "M", "M" ], run = "plugin mount", desc = "Mount" },
    #
    # # { on = [ "<C-m>", "m" ], run = "plugin gvfs -- select-then-mount", desc = "Mount" },
    # { on = [ "<C-m>", "m" ], run = "plugin gvfs -- select-then-mount --jump", desc = "Mount(gvfs) && Jump" },
    #
    # { on = [ "<C-m>", "R" ], run = "plugin gvfs -- remount-current-cwd-device", desc = "Remount cwd" },
    # { on = [ "<C-m>", "u" ], run = "plugin gvfs -- select-then-unmount --eject", desc = "Eject" },
    # { on = [ "<C-m>", "U" ], run = "plugin gvfs -- select-then-unmount --eject --force", desc = "Force eject/unmount" },
    #
    # { on = [ "<C-m>", "a" ], run = "plugin gvfs -- add-mount", desc = "Add a GVFS mount URI" },
    # { on = [ "<C-m>", "e" ], run = "plugin gvfs -- edit-mount", desc = "Edit a GVFS mount URI" },
    # { on = [ "<C-m>", "r" ], run = "plugin gvfs -- remove-mount", desc = "Remove a GVFS mount URI" },
    #
    # # Jump
    # { on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device --automount", desc = "Automount && Jump" },
    # { on = [ "`", "`" ], run = "plugin gvfs -- jump-back-prev-cwd", desc = "Jump back" },

    # Smart switch
    { on = "2", run = "plugin smart-switch 1", desc = "Switch or create tab 2" },

    # Toggle panel
    # { on = "T", run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },
    { on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
    { on = "<C-t>", run = "plugin toggle-pane min-preview", desc = "Minimize or restore the preview pane" },

    # Bookmark
    # { on = [ "b", "a" ], run = "plugin mactag add" },
    # { on = [ "b", "r" ], run = "plugin mactag remove" },
    { on = [ "b", "b" ], run = "plugin whoosh jump_by_key", desc = "Jump bookmark by key" },
    { on = [ "B" ], run = "plugin whoosh jump_by_fzf", desc = "Fuzzy search for bookmarks" },
    { on = [ "b", "a" ], run = "plugin whoosh save", desc = "Add bookmark (hovered)" },
    { on = [ "b", "A" ], run = "plugin whoosh save_cwd", desc = "Add bookmark (cwd)" },
    { on = [ "b", "t" ], run = "plugin whoosh save_temp", desc = "Add temp bookmark (hovered)" },
    { on = [ "b", "T" ], run = "plugin whoosh save_cwd_temp", desc = "Add temp bookmark (cwd)" },
    { on = [ "b", "k" ], run = "plugin whoosh jump_key_k", desc = "Jump bookmark with key k" },
    { on = [ "b", "f" ], run = "plugin whoosh jump_by_fzf", desc = "Jump bookmark by fzf" },
    { on = [ "b", "d" ], run = "plugin whoosh delete_by_key", desc = "Delete bookmark by key" },
    { on = [ "b", "D" ], run = "plugin whoosh delete_by_fzf", desc = "Delete bookmark by fzf" },
    { on = [ "b", "C" ], run = "plugin whoosh delete_all", desc = "Delete all bookmarks" },
    { on = [ "b", "r" ], run = "plugin whoosh rename_by_key", desc = "Rename bookmark by key" },
    { on = [ "b", "R" ], run = "plugin whoosh rename_by_fzf", desc = "Rename bookmark by fzf" },
]
