#:schema https://yazi-rs.github.io/schemas/theme.json

[flavor]
light = "noctalia"
dark  = "noctalia"
# dark  = "catppuccin-macchiato"
# light = "catppuccin-latte"

[icon]
prepend_exts = [
    { name = "age", text = "󰈡" }
]
